# Site settings
title: Alan Berotti
email: 
description: This is a blog. Idk what to say but it was fun to make...
baseurl: "/words" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: username
github_username: username

author: Alan Berotti

# Build settings
markdown: kramdown

# redcarpet:
#   extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]